name: open-amp-demo
channels:
  - conda-forge
  - pytorch
dependencies:
  - pytorch::pytorch
  - torchaudio
  - pandas
  - numpy
  - librosa
  - matplotlib
  - wandb
  - tqdm
  - pip
  - pip:
      - auraloss
      - soundfile