source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins

# deployment --------
gem "jekyll-include-cache", group: :jekyll_plugins

# local testing ---------------
# gem "jekyll"
# gem "minimal-mistakes-jekyll"
# gem "webrick", "~> 1.8"
# group :jekyll_plugins do
#   gem "jekyll-feed", "~> 0.12"
# end
# platforms :mingw, :x64_mingw, :mswin, :jruby do
#   gem "tzinfo", ">= 1", "< 3"
#   gem "tzinfo-data"
# end
# gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
# gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]


